  bitcoind:
    image: docker.io/ruimarinho/bitcoin-core:22
    command:
      - -regtest
      - -server
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=rpcuser
      - -rpcpassword=rpcpassword
      - -fallbackfee=0.0002
    ports:
      - '18443:18443'
  bitcoin-cli:
    image: docker.io/ruimarinho/bitcoin-core:22
    command:
      - /bin/bash
      - -c
      - |
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Alice
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Bob
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Charlie
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Dave
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Eve
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Ferdie
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword loadwallet Alice
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword loadwallet Bob
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword loadwallet Charlie
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword loadwallet Dave
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword loadwallet Eve
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword loadwallet Ferdie
        ALICE_ADDRESS=$$(bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword -rpcwallet=Alice getnewaddress)
        # coins need 100 confirmations to be spendable
        bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword generatetoaddress 101 $${ALICE_ADDRESS}
  electrs:
    image: docker.io/interlayhq/electrs:latest
    command:
      - electrs
      - -vvv
      - --network
      - regtest
      - --jsonrpc-import
      - --cors
      - '*'
      - --cookie
      - 'rpcuser:rpcpassword'
      - --daemon-rpc-addr
      - 'bitcoind:18443'
      - --http-addr
      - '[::0]:3002'
      - --index-unspendables
    restart: always
    ports:
      - '3002:3002'
  oracle:
    image: docker.io/interlayhq/interbtc-clients:oracle-parachain-metadata-kintsugi-testnet-master
    command:
      - /bin/sh
      - -c
      - |
        # prepare ./config.json
        echo "$$ORACLE_CONFIG" > config.json
        # start oracle
        /usr/local/bin/oracle-parachain-metadata-kintsugi-testnet \
        --keyring charlie \
        --btc-parachain-url 'ws://parachain-2000-0:9944' \
        --oracle-config config.json
    environment:
      RUST_LOG: info
      ORACLE_CONFIG: |
        {
            "currencies": {
                "BTC": {
                    "name": "Bitcoin",
                    "decimals": 8
                },
                "DOT": {
                    "name": "Polkadot",
                    "decimals": 10
                },
                "INTR": {
                    "name": "Interlay",
                    "decimals": 10
                },
                "KSM": {
                    "name": "Kusama",
                    "decimals": 12
                },
                "KINT": {
                    "name": "Kintsugi",
                    "decimals": 12
                }
            },
            "prices": [
                {
                    "pair": [
                        "BTC",
                        "DOT"
                    ],
                    "value": 230
                },
                {
                    "pair": [
                        "BTC",
                        "INTR"
                    ],
                    "value": 230
                },
                {
                    "pair": [
                        "BTC",
                        "KSM"
                    ],
                    "value": 230
                },
                {
                    "pair": [
                        "BTC",
                        "KINT"
                    ],
                    "value": 230
                }
            ]
        }
  vault_1:
    image: interlayhq/interbtc-clients:vault-parachain-metadata-kintsugi-testnet-master
    command:
      - /bin/sh
      - -c
      - |
        # charlie_stash
        echo '{"vault_1": "0x66256c4e2f90e273bf387923a9a7860f2e9f47a1848d6263de512f7fb110fc08"}' > keyfile.json
        echo "Sleeping..."
        # sleep for 30s to wait for bitcoin to create the Charlie wallet
        # and also to ensure that the issue period and redeem period are set
        sleep 30
        /usr/local/bin/vault-parachain-metadata-kintsugi-testnet --keyfile="keyfile.json" --keyname="vault_1" --auto-register=KSM=10000000000000 --auto-register=KINT=180000000000000 --btc-parachain-url 'ws://parachain-2000-0:9944'
    environment: &client-env
      BITCOIN_RPC_URL: http://bitcoind:18443
      BITCOIN_RPC_USER: rpcuser
      BITCOIN_RPC_PASS: rpcpassword
      RUST_LOG: info
  vault_2:
    image: 'interlayhq/interbtc-clients:vault-parachain-metadata-kintsugi-testnet-master'
    command:
      - /bin/sh
      - -c
      - |
        # dave_stash
        echo '{"vault_2": "0x8766312742c2ebdc78713dab36f8eb328d30d053d702da8167e4672d615f421e"}' > keyfile.json
        echo "Sleeping..."
        # sleep for 30s to wait for bitcoin to create the Dave wallet
        # and also to ensure that the issue period and redeem period are set
        sleep 30
        /usr/local/bin/vault-parachain-metadata-kintsugi-testnet --keyfile="keyfile.json" --keyname=vault_2 --auto-register=KSM=10000000000000 --auto-register=KINT=180000000000000 --no-issue-execution --btc-parachain-url 'ws://parachain-2000-0:9944'
    environment:
      <<: *client-env
  vault_3:
    image: 'interlayhq/interbtc-clients:vault-parachain-metadata-kintsugi-testnet-master'
    command:
      - /bin/sh
      - -c
      - |
        # eve_stash
        echo '{"vault_3": "0x26eda5da160bf8e1810336f97a31d3271fe8b386c4e5b7b4367e55ea33f297d0"}' > keyfile.json
        echo "Sleeping..."
        # sleep for 30s to wait for bitcoin to create the Eve wallet
        # and also to ensure that the issue period and redeem period are set
        sleep 30
        /usr/local/bin/vault-parachain-metadata-kintsugi-testnet --keyfile="keyfile.json" --keyname=vault_3 --auto-register=KSM=10000000000000 --auto-register=KINT=180000000000000 --no-issue-execution --btc-parachain-url 'ws://parachain-2000-0:9944'
    environment:
      <<: *client-env
  vault_to_liquidate:
    image: 'interlayhq/interbtc-clients:vault-parachain-metadata-kintsugi-testnet-master'
    command:
      - /bin/sh
      - -c
      - |
        # ferdie_stash
        echo '{"vault_to_liquidate": "0x32a1ce8b76ea5820c59663458a0f5dd90b70d9c69beff048ddcdb6daa451afd9"}' > keyfile.json
        echo "Sleeping..."
        # sleep for 30s to wait for bitcoin to create the Ferdie wallet
        # and also to ensure that the issue period and redeem period are set
        sleep 30
        /usr/local/bin/vault-parachain-metadata-kintsugi-testnet --keyfile="keyfile.json" --keyname=vault_to_liquidate --auto-register=KSM=10000000000000 --auto-register=KINT=180000000000000 --btc-parachain-url 'ws://parachain-2000-0:9944'
    environment:
      <<: *client-env
  vault_to_ban:
    image: 'interlayhq/interbtc-clients:vault-parachain-metadata-kintsugi-testnet-master'
    command:
      - /bin/sh
      - -c
      - |
        # ferdie
        echo '{"vault_to_ban": "0x42438b7883391c05512a938e36c2df0131e088b3756d6aa7a755fbff19d2f842"}' > keyfile.json
        echo "Sleeping..."
        # sleep for 30s to wait for bitcoin to create the Ferdie wallet
        # and also to ensure that the issue period and redeem period are set
        sleep 30
        /usr/local/bin/vault-parachain-metadata-kintsugi-testnet --keyfile="keyfile.json" --keyname=vault_to_ban --auto-register=KSM=10000000000000 --auto-register=KINT=180000000000000 --btc-parachain-url 'ws://parachain-2000-0:9944'
    environment:
      <<: *client-env
